### ISSUE TITLE
prequisite on Software::License::CC_BY_SA_3_0

### ISSUE THREAD

**Issue by karenetheridge** [cpants/Module-CPANTS-Analyse#23]
I don't understand why Software::License::CC_BY_SA_3_0 is listed as a prerequisite of MCA. (There are many other Software::License::* modules distributed independently - are you intending to require all of them?)

Would it be possible to simply try to `require` the `Software::License::$license` module in `lib/Module/CPANTS/Kwalitee/License.pm` only as needed (and print a warning if it is not installed)?

**Comment by charsbar** [comment]
> I don't understand why Software::License::CC_BY_SA_3_0 is listed as a prerequisite of MCA.

Because there was a request (see https://rt.cpan.org/Public/Bug/Display.html?id=92257), and because ::CCpack didn't have a version in the main module previously (see http://search.cpan.org/~bbyrd/Software-License-CCpack-1.0/), but ... yeah, it wasn't worth adding because only a few distributions use CC licenses. I should have added this to www-cpants instead.

> (There are many other Software::License::* modules distributed independently - are you intending to require all of them?)

No for MCA, though I might possibly add some to www-cpants to improve analysis/statistics. 

> Would it be possible to simply try to require the Software::License::$license module in lib/Module/CPANTS/Kwalitee/License.pm only as needed (and print a warning if it is not installed)?

Could you explain this? MCA just asks Software::LicenseUtils to guess licenses, and doesn't care what licenses it recognizes.

**Comment by karenetheridge** [comment]
> Could you explain this? MCA just asks Software::LicenseUtils to guess licenses, and doesn't care what licenses it recognizes.

Oh sorry, I misguessed what the code was doing :)

**Comment by charsbar** [comment]
Dropped ::CCpack. Thanks for the heads-up!

**Comment by dolmen** [comment]
Thanks @charsbar !
